name: Build and push

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        ##login-server: dockerhub.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t magohl/whoamicore:${GITHUB_REF#refs/tags/}
        docker push magohl/whoamicore:${GITHUB_REF#refs/tags/}


    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'magnus-aks'
        cluster-name: 'kramerica-k8s'
      id: login

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          .manifests/deployment.yaml
          .manifests/service.yaml
        images: |
          index.docker.io/magohl/whoamicore:${GITHUB_REF#refs/tags/}
